
[build]
  publish = "dist"
  command = "npm run build"

# Ottimizzazioni per SEO e performance
[build.environment]
  NODE_VERSION = "18"

# Headers per SEO e sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers specifici per file statici
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect per SEO
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# Redirect per pagine principali
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# Redirect per vecchi URL (se esistono)
[[redirects]]
  from = "/cane"
  to = "/analisi-cane"
  status = 301

[[redirects]]
  from = "/gatto"
  to = "/analisi-gatto"
  status = 301

# Redirect per errori 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Compressione gzip
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"
